// Code generated by goctl. DO NOT EDIT.
// Source: talk.proto

package server

import (
	"gotalk/gotalk"
	"gotalk/internal/logic"
	"gotalk/internal/svc"
)

type ChatServiceServer struct {
	svcCtx *svc.ServiceContext
	gotalk.UnimplementedChatServiceServer
}

func NewChatServiceServer(svcCtx *svc.ServiceContext) *ChatServiceServer {
	return &ChatServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ChatServiceServer) Send(stream gotalk.ChatService_SendServer) error {
	l := logic.NewSendLogic(stream.Context(), s.svcCtx)
	return l.Send(stream)
}

func (s *ChatServiceServer) Listener(in *gotalk.SessionId, stream gotalk.ChatService_ListenerServer) error {
	l := logic.NewListenerLogic(stream.Context(), s.svcCtx)
	return l.Listener(in, stream)
}
