// Code generated by goctl. DO NOT EDIT.
// Source: gotalkgRPC.proto

package server

import (
	"context"
	"gotalk/gotalk"
	"gotalk/internal/logic"
	"gotalk/internal/svc"
)

type HelloServer struct {
	svcCtx *svc.ServiceContext
	gotalk.UnimplementedHelloServer
}

func NewHelloServer(svcCtx *svc.ServiceContext) *HelloServer {
	return &HelloServer{
		svcCtx: svcCtx,
	}
}

func (s *HelloServer) Hi(ctx context.Context, in *gotalk.Request) (*gotalk.Response, error) {
	l := logic.NewHiLogic(ctx, s.svcCtx)
	return l.Hi(in)
}
