// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: healthCheck.proto

package gotalk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestHealthCheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestHealthCheck) Reset() {
	*x = RequestHealthCheck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_healthCheck_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestHealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHealthCheck) ProtoMessage() {}

func (x *RequestHealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_healthCheck_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHealthCheck.ProtoReflect.Descriptor instead.
func (*RequestHealthCheck) Descriptor() ([]byte, []int) {
	return file_healthCheck_proto_rawDescGZIP(), []int{0}
}

type ResponseHealthCheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResponseHealthCheck) Reset() {
	*x = ResponseHealthCheck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_healthCheck_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseHealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHealthCheck) ProtoMessage() {}

func (x *ResponseHealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_healthCheck_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHealthCheck.ProtoReflect.Descriptor instead.
func (*ResponseHealthCheck) Descriptor() ([]byte, []int) {
	return file_healthCheck_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseHealthCheck) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_healthCheck_proto protoreflect.FileDescriptor

var file_healthCheck_proto_rawDesc = []byte{
	0x0a, 0x11, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x6f, 0x74, 0x61, 0x6c, 0x6b, 0x22, 0x14, 0x0a, 0x12, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x22, 0x27, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x50, 0x0a, 0x0b, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x41, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x12, 0x1a, 0x2e, 0x67, 0x6f, 0x74, 0x61, 0x6c, 0x6b, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x1a,
	0x1b, 0x2e, 0x67, 0x6f, 0x74, 0x61, 0x6c, 0x6b, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2f, 0x67, 0x6f, 0x74, 0x61, 0x6c, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_healthCheck_proto_rawDescOnce sync.Once
	file_healthCheck_proto_rawDescData = file_healthCheck_proto_rawDesc
)

func file_healthCheck_proto_rawDescGZIP() []byte {
	file_healthCheck_proto_rawDescOnce.Do(func() {
		file_healthCheck_proto_rawDescData = protoimpl.X.CompressGZIP(file_healthCheck_proto_rawDescData)
	})
	return file_healthCheck_proto_rawDescData
}

var file_healthCheck_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_healthCheck_proto_goTypes = []interface{}{
	(*RequestHealthCheck)(nil),  // 0: gotalk.RequestHealthCheck
	(*ResponseHealthCheck)(nil), // 1: gotalk.ResponseHealthCheck
}
var file_healthCheck_proto_depIdxs = []int32{
	0, // 0: gotalk.HealthCheck.health:input_type -> gotalk.RequestHealthCheck
	1, // 1: gotalk.HealthCheck.health:output_type -> gotalk.ResponseHealthCheck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_healthCheck_proto_init() }
func file_healthCheck_proto_init() {
	if File_healthCheck_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_healthCheck_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestHealthCheck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_healthCheck_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseHealthCheck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_healthCheck_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_healthCheck_proto_goTypes,
		DependencyIndexes: file_healthCheck_proto_depIdxs,
		MessageInfos:      file_healthCheck_proto_msgTypes,
	}.Build()
	File_healthCheck_proto = out.File
	file_healthCheck_proto_rawDesc = nil
	file_healthCheck_proto_goTypes = nil
	file_healthCheck_proto_depIdxs = nil
}
